<a href="https://colab.research.google.com/github/24cse150rishirajsahu/DMDW-lab-assignment-/blob/main/ass3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/Book1.csv')

In [4]:
df

    roll  name  age gen branch sec
0       1   aa   19   m    cse   a
1       2   bb   20   m    ece   b
2       3   cc   21   f    cse   b
3       4   dd   19   f    cse   a
4       5   ee   20   m    cse   b
5       6   ff   21   m    ece   c
6       7   gg   19   f    bio   b
7       8   hh   20   f    eee   d
8       9   ii   22   m    bio   b
9      10   jj   23   f    eee   a
10     11   kk   21   m    bio   d
11     12   ll   22   f    cse   c
12     13   mm   23   m    ece   d
13     14   nn   19   f    bio   a

In [6]:
df.head()

   roll  name  age gen branch sec
0      1   aa   19   m    cse   a
1      2   bb   20   m    ece   b
2      3   cc   21   f    cse   b
3      4   dd   19   f    cse   a
4      5   ee   20   m    cse   b

In [7]:
df.tail()

    roll  name  age gen branch sec
9      10   jj   23   f    eee   a
10     11   kk   21   m    bio   d
11     12   ll   22   f    cse   c
12     13   mm   23   m    ece   d
13     14   nn   19   f    bio   a

In [8]:
df.head(7)

   roll  name  age gen branch sec
0      1   aa   19   m    cse   a
1      2   bb   20   m    ece   b
2      3   cc   21   f    cse   b
3      4   dd   19   f    cse   a
4      5   ee   20   m    cse   b
5      6   ff   21   m    ece   c
6      7   gg   19   f    bio   b

In [9]:
df.tail(6)

    roll  name  age gen branch sec
8       9   ii   22   m    bio   b
9      10   jj   23   f    eee   a
10     11   kk   21   m    bio   d
11     12   ll   22   f    cse   c
12     13   mm   23   m    ece   d
13     14   nn   19   f    bio   a

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    14 non-null     int64
 1   name    14 non-null     object
 2   age     14 non-null     int64
 3   gen     14 non-null     object
 4   branch  14 non-null     object
 5   sec     14 non-null     object
dtypes: int64(2), object(4)
memory usage: 804.0+ bytes

In [11]:
df.describe()

         roll         age
count  14.0000  14.000000
mean    7.5000  20.642857
std     4.1833   1.446861
min     1.0000  19.000000
25%     4.2500  19.250000
50%     7.5000  20.500000
75%    10.7500  21.750000
max    14.0000  23.000000

In [12]:
df.shape

(14, 6)

In [13]:
df.columns

Index(['roll ', 'name', 'age', 'gen', 'branch', 'sec'], dtype='object')

In [14]:
df.dtypes

roll       int64
name      object
age        int64
gen       object
branch    object
sec       object
dtype: object

In [16]:
df.isnull()

    roll    name    age    gen  branch    sec
0   False  False  False  False   False  False
1   False  False  False  False   False  False
2   False  False  False  False   False  False
3   False  False  False  False   False  False
4   False  False  False  False   False  False
5   False  False  False  False   False  False
6   False  False  False  False   False  False
7   False  False  False  False   False  False
8   False  False  False  False   False  False
9   False  False  False  False   False  False
10  False  False  False  False   False  False
11  False  False  False  False   False  False
12  False  False  False  False   False  False
13  False  False  False  False   False  False

In [17]:
df.loc(0)

In [18]:
ages =df['age']

In [19]:
ages

0     19
1     20
2     21
3     19
4     20
5     21
6     19
7     20
8     22
9     23
10    21
11    22
12    23
13    19
Name: age, dtype: int64

In [20]:
adults = df[df['age'] > 20]
print("those whose are elder tham 20 years \n",adults)

those whose are elder tham 20 years
     roll  name  age gen branch sec
2       3   cc   21   f    cse   b
5       6   ff   21   m    ece   c
8       9   ii   22   m    bio   b
9      10   jj   23   f    eee   a
10     11   kk   21   m    bio   d
11     12   ll   22   f    cse   c
12     13   mm   23   m    ece   d

In [22]:
adults = df[(df['age'] >= 19) & (df['age'] <= 20)]
print("those whose are age in 19 to 20 years \n",adults)

those whose are age in 19 to 20 years
     roll  name  age gen branch sec
0       1   aa   19   m    cse   a
1       2   bb   20   m    ece   b
3       4   dd   19   f    cse   a
4       5   ee   20   m    cse   b
6       7   gg   19   f    bio   b
7       8   hh   20   f    eee   d
13     14   nn   19   f    bio   a

In [24]:
male_candidates = df[df['gen'] == 'm']
print("Male candidates: \n", male_candidates)

Male candidates:
     roll  name  age gen branch sec
0       1   aa   19   m    cse   a
1       2   bb   20   m    ece   b
4       5   ee   20   m    cse   b
5       6   ff   21   m    ece   c
8       9   ii   22   m    bio   b
10     11   kk   21   m    bio   d
12     13   mm   23   m    ece   d

In [25]:
male_adults_19_20 = df[(df['gen'] == 'm') & (df['age'] >= 19) & (df['age'] <= 20)]
print("Male candidates aged 19-20: \n", male_adults_19_20)

Male candidates aged 19-20:
    roll  name  age gen branch sec
0      1   aa   19   m    cse   a
1      2   bb   20   m    ece   b
4      5   ee   20   m    cse   b

In [26]:
sorted_by_age = df.sort_values(by='age', ascending=True)
print("Students sorted by age (lower to higher):\n", sorted_by_age)

Students sorted by age (lower to higher):
     roll  name  age gen branch sec
0       1   aa   19   m    cse   a
3       4   dd   19   f    cse   a
6       7   gg   19   f    bio   b
13     14   nn   19   f    bio   a
7       8   hh   20   f    eee   d
4       5   ee   20   m    cse   b
1       2   bb   20   m    ece   b
2       3   cc   21   f    cse   b
5       6   ff   21   m    ece   c
10     11   kk   21   m    bio   d
11     12   ll   22   f    cse   c
8       9   ii   22   m    bio   b
9      10   jj   23   f    eee   a
12     13   mm   23   m    ece   d